baseUrl = "http://ziggyswift.com/"
languageCode = "en-us"
title = "Ziggy Swift"
theme = "hyde-hyde"


[Menus]
  main = [
      {Name = "Posts", URL = "/post", Weight=100},
      {Name = "Story Time!", URL = "/story-time", Weight=200},
      {Name = "About Ziggy", URL = "/about", Weight=300}
  ]

[params]
	author = "Ziggy Swift"
  	layoutReverse = true
	description = "Lets go Clubbin'."
	authorimage = "/2011/08/ziggy-lulz-300x300.png"
[params.social]
	twitter = "ziggyswift"
#	gravatar = "ziggy@ziggyswift.com"

